apiVersion: v1
kind: Namespace
metadata:
  name: netops-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-customer-alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-customer-beta