apiVersion: apps/v1
kind: Deployment
metadata:
  name: netops-frontend
  namespace: netops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netops-frontend
  template:
    metadata:
      labels:
        app: netops-frontend
    spec:
      containers:
      - name: ui-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "25m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "32Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
